
#Super
dataset: iSAID
backbone: ViT-B/16-384 #ViT-B/16-384
bs: 2
vit_depth: 10
test_n: 1000
epochs: 40
height: 256                    #default:480
width: 256                    #default:480
lr: 0.0005 #0.001
fg_num: 5
unlabeled: 5
agg_depth: 6
filter: 0.7
network: agmtr # super_baseline
pair_lossW: 0.02
split: 0 #0,1,2
shot: 1
